services:
  - type: web
    name: app-prediction
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn App_prediction.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: App_prediction.settings
